visit = ['Paris','Daytona','Japan','Columbia','Taco Bell']
print(visit)
print(sorted(visit))
print(visit)
visit.reverse()
print(visit)
visit.reverse()
print(visit)
visit.sort()
print(visit)
visit.sort(reverse=True)
print(visit)

water = ['nile','Red Sea', 'Indian', 'Atlantic', 'Pacific']
print(f'{water[0].title()} river is the longest river in the world')
print('Which these is an ocean?')
print(water[-1])
water[2] = 'Artic'
print(water)
water.append('Niagra')
print(water)
del water[2]
print(water)
print(water.pop())
thisisthepacific = water.pop(3)
print(thisisthepacific)
water.remove('Red Sea')
print(water)
print('--------------------------------------------')
water.append('dirt')
water.append('sand')
water.append('air')
print(sorted(water))
print(water)
water.sort()
print(water)
water.reverse()
print(water)
print(len(water))
water.sort(reverse=True)
print(water)